version: '3'

services:

  db:
    image: mysql:8.2.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: node
    container_name: app
    restart: always
    networks:
      - node-network
    volumes:
      - ./node:/usr/app/node
    tty: true
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:8080"
    command: nginx -g 'daemon off;'
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
